---
# handlers file for icinga2-ansible-web-ui
- name: restart icinga2
  become: true
  service:
    name: icinga2
    state: restarted
    enabled: yes

- name: restart httpd
  become: true
  service:
    name: httpd
    state: restarted
    enabled: yes
